name: Auto Commit and Push

on:
  push:
    paths:
      - "images"
    branches:
      - main

jobs:
  commit_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and Push
        run: |
          git add -A
          git commit -m "Add new image" || true # Continue even if no changes are detected
          git push
